events:
  service_name: "events-service"
  pulsar:
    broker:
      url:
  event:
    producer:
      topic: "events-service-topic"
    consumer:
      subscription:
        name: "goletan-events-service-subscription"