service_name: "events-service"

pulsar:
  broker:
    url: "pulsar://pulsar:6650"

event:
  producer:
    topic: "events-service-topic"
  consumer:
    subscription:
      name: "goletan-events-service-subscription"