service_name: "events"

pulsar:
  broker:
    url: "pulsar://pulsar:6650"

event:
  producer:
    topic: "persistent://public/default/events-service-topic"
  consumer:
    subscription:
      name: "goletan-events-subscription"

grpc:
  address: "events:50051"

http:
  address: "events:443"

client:
  strategy: "grpc"