service_name: "events-service"

pulsar:
  broker:
    url: "pulsar://pulsar:6650"

event:
  producer:
    topic: "persistent://public/default/events-service-topic"
  consumer:
    subscription:
      name: "goletan-events-subscription"

grpc:
  address: "0.0.0.0:50051"

client:
  strategy: "grpc"